<?php

namespace TNM\USSD\Test;

use Illuminate\Foundation\Testing\RefreshDatabase;
use Illuminate\Foundation\Testing\WithFaker;
use Tests\TestCase;
use TNM\USSD\Http\Request;
use TNM\USSD\Models\Session;
use TNM\USSD\Screen;

class ScreenTest extends TestCase
{
    use RefreshDatabase, WithFaker;
    /**
     * @var \Mockery\LegacyMockInterface|\Mockery\MockInterface|Request
     */
    private $request;

    protected function setUp(): void
    {
        parent::setUp(); // TODO: Change the autogenerated stub
//        $this->mockRequest();
    }

    public function testRender()
    {
        $request = \Mockery::mock(Request::class);
        $request->shouldReceive('construct')
            ->andSet('trail', new Session([
                'session_id' => $this->faker->numerify("######")
            ]));
        dd($request);
//        $request = new Request();
        $screen = Screen::getInstance($request);

        dd($screen);
    }


//    public function testOutOfRange()
//    {
//
//    }
//
//    public function testHasPayload()
//    {
//
//    }
//
//    public function testHandle()
//    {
//
//    }
//
//    public function testGetItemAt()
//    {
//
//    }
//
//    public function testPrevious()
//    {
//
//    }
//
//    public function testWithinRange()
//    {
//
//    }
    protected function mockRequest(): Request
    {
        $request = \Mockery::mock(Request::class);
        $request->shouldReceive('construct')
            ->andSet('session_id', $this->faker->numerify("######"))
            ->andSet('msisdn', '265888800900');
        return $request;
    }
}
